# Generated by Django 3.2 on 2021-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_maneger_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maneger',
            name='cpf',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
